export { default as Navigation } from './Navigation'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Modules } from './Modules'
export { default as Benefits } from './Benefits'
export { default as Testimonials } from './Testimonials'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'
