export const landingPageContent = {
  hero: {
    badge: "🎒 New Learning Adventure",
    headline: "Where Learning Becomes an Epic Adventure!",
    subheadline: "Join thousands of kids on a magical journey through math, language, time-telling, and more with Little Nezha Academy.",
    description: "Interactive games designed by education experts to make learning irresistible. Safe, fun, and proven to spark curiosity.",
    primaryCTA: "Start Free Adventure",
    secondaryCTA: "Watch Demo",
    trustBadges: [
      "✓ 100% Safe & Ad-Free",
      "✓ Loved by 50,000+ Kids",
      "✓ Parent-Approved",
    ],
  },

  features: {
    sectionBadge: "Why Choose Us",
    headline: "Learning That Feels Like Play",
    subheadline: "Carefully crafted modules that transform screen time into brain time",
    items: [
      {
        icon: "🎯",
        title: "Expert-Designed",
        description: "Created by educators and child psychologists for maximum engagement and retention",
        color: "primary",
      },
      {
        icon: "🎮",
        title: "Gamified Learning",
        description: "Turn every lesson into an exciting quest with rewards, levels, and achievements",
        color: "secondary",
      },
      {
        icon: "📊",
        title: "Progress Tracking",
        description: "Parents get detailed insights into their child's learning journey and milestones",
        color: "trust",
      },
      {
        icon: "🛡️",
        title: "Safe Environment",
        description: "COPPA compliant, ad-free, and designed with your child's safety as top priority",
        color: "success",
      },
      {
        icon: "🌈",
        title: "Adaptive Learning",
        description: "AI-powered difficulty adjustment ensures every child learns at their perfect pace",
        color: "accent",
      },
      {
        icon: "👨‍👩‍👧‍👦",
        title: "Multi-Child Support",
        description: "One account, unlimited kids. Each gets their own personalized learning path",
        color: "primary",
      },
    ],
  },

  modules: {
    sectionBadge: "Explore Our Modules",
    headline: "A World of Learning Adventures",
    subheadline: "Each module is a gateway to mastering essential skills through interactive play",
    items: [
      {
        id: "clock-trainer",
        icon: "⏰",
        title: "Analog Clock Trainer",
        description: "Master time-telling through interactive games and real-world scenarios",
        features: ["12 & 24-hour formats", "Interactive clock hands", "Time challenges", "Real-world practice"],
        color: "primary",
        ageRange: "5-8 years",
        difficulty: "Beginner to Advanced",
      },
      {
        id: "math-lab",
        icon: "🧮",
        title: "Math Lab",
        description: "From counting to multiplication, make math magical and fun",
        features: ["Addition & Subtraction", "Multiplication tables", "Word problems", "Visual math games"],
        color: "trust",
        ageRange: "4-10 years",
        difficulty: "All Levels",
      },
      {
        id: "language-explorer",
        icon: "📚",
        title: "Language Explorer",
        description: "Build vocabulary, spelling, and reading comprehension with exciting stories",
        features: ["Phonics practice", "Spelling bees", "Story adventures", "Vocabulary builder"],
        color: "secondary",
        ageRange: "4-12 years",
        difficulty: "All Levels",
      },
      {
        id: "puzzle-palace",
        icon: "🧩",
        title: "Puzzle Palace",
        description: "Sharpen logic and problem-solving skills with mind-bending challenges",
        features: ["Logic puzzles", "Pattern recognition", "Memory games", "Critical thinking"],
        color: "accent",
        ageRange: "6-12 years",
        difficulty: "Progressive",
      },
      {
        id: "science-station",
        icon: "🔬",
        title: "Science Station",
        description: "Explore the wonders of science through virtual experiments and discovery",
        features: ["Virtual experiments", "Nature exploration", "Space adventures", "Body & health"],
        color: "success",
        ageRange: "7-12 years",
        difficulty: "All Levels",
      },
      {
        id: "art-studio",
        icon: "🎨",
        title: "Creative Art Studio",
        description: "Unleash creativity with digital drawing, music, and storytelling tools",
        features: ["Digital painting", "Music creation", "Story builder", "Animation basics"],
        color: "primary",
        ageRange: "5-12 years",
        difficulty: "All Levels",
      },
    ],
  },

  benefits: {
    sectionBadge: "The Nezha Difference",
    headline: "More Than Just Games",
    subheadline: "We're building the next generation of curious, confident learners",
    items: [
      {
        icon: "🧠",
        stat: "95%",
        title: "Knowledge Retention",
        description: "Our interactive approach leads to significantly higher retention compared to traditional methods",
      },
      {
        icon: "⭐",
        stat: "4.9/5",
        title: "Parent Rating",
        description: "Trusted by thousands of parents who see real progress in their children",
      },
      {
        icon: "🎓",
        stat: "50K+",
        title: "Active Learners",
        description: "Kids worldwide are discovering the joy of learning with Little Nezha",
      },
      {
        icon: "📈",
        stat: "2x Faster",
        title: "Learning Speed",
        description: "Children learn concepts twice as fast through our gamified approach",
      },
    ],
  },

  testimonials: {
    sectionBadge: "What Parents Say",
    headline: "Loved by Kids, Trusted by Parents",
    subheadline: "Real stories from real families",
    items: [
      {
        quote: "My 7-year-old daughter went from struggling with telling time to teaching her younger brother in just 3 weeks! The Clock Trainer is pure magic.",
        author: "Sarah Chen",
        role: "Mom of 2",
        avatar: "SC",
        rating: 5,
      },
      {
        quote: "Finally, a learning app that my son actually begs to use. His math skills have improved dramatically, and I love the progress reports.",
        author: "Michael Rodriguez",
        role: "Dad & Teacher",
        avatar: "MR",
        rating: 5,
      },
      {
        quote: "As a pediatrician, I'm cautious about screen time. Little Nezha Academy is the only app I actively recommend to parents. It's educational gold.",
        author: "Dr. Emily Watson",
        role: "Pediatrician & Mom",
        avatar: "EW",
        rating: 5,
      },
      {
        quote: "The multi-child feature is a lifesaver! All three of my kids use it at their own levels. Worth every penny.",
        author: "James Park",
        role: "Father of 3",
        avatar: "JP",
        rating: 5,
      },
    ],
  },

  pricing: {
    sectionBadge: "Simple Pricing",
    headline: "Start Free, Upgrade Anytime",
    subheadline: "No hidden fees. Cancel anytime. 30-day money-back guarantee.",
    plans: [
      {
        name: "Free Explorer",
        price: "$0",
        period: "forever",
        description: "Perfect for trying out Little Nezha",
        features: [
          "Access to 2 modules",
          "Basic progress tracking",
          "1 child profile",
          "Community support",
        ],
        cta: "Start Free",
        popular: false,
      },
      {
        name: "Family Plan",
        price: "$9.99",
        period: "per month",
        description: "Full access for the whole family",
        features: [
          "All modules unlocked",
          "Unlimited child profiles",
          "Advanced analytics",
          "Priority support",
          "Offline mode",
          "No ads ever",
        ],
        cta: "Start 14-Day Trial",
        popular: true,
      },
      {
        name: "Yearly Family",
        price: "$99",
        period: "per year",
        description: "Save 17% with annual billing",
        features: [
          "Everything in Family Plan",
          "2 months free",
          "Early access to new modules",
          "Premium parent resources",
          "Dedicated account manager",
        ],
        cta: "Get Annual Plan",
        popular: false,
      },
    ],
  },

  cta: {
    headline: "Ready to Transform Learning Time?",
    subheadline: "Join 50,000+ families who've discovered the joy of learning",
    primaryCTA: "Start Your Free Adventure",
    secondaryCTA: "Schedule a Demo",
    features: [
      "✓ No credit card required",
      "✓ 14-day free trial",
      "✓ Cancel anytime",
    ],
  },

  footer: {
    tagline: "Making learning an adventure, one child at a time.",
    links: {
      product: [
        { label: "Features", href: "#features" },
        { label: "Modules", href: "#modules" },
        { label: "Pricing", href: "#pricing" },
        { label: "FAQ", href: "#faq" },
      ],
      company: [
        { label: "About Us", href: "/about" },
        { label: "Our Team", href: "/team" },
        { label: "Careers", href: "/careers" },
        { label: "Blog", href: "/blog" },
      ],
      resources: [
        { label: "Parent Guide", href: "/guide" },
        { label: "Help Center", href: "/help" },
        { label: "Safety", href: "/safety" },
        { label: "Research", href: "/research" },
      ],
      legal: [
        { label: "Privacy Policy", href: "/privacy" },
        { label: "Terms of Service", href: "/terms" },
        { label: "COPPA Compliance", href: "/coppa" },
        { label: "Cookie Policy", href: "/cookies" },
      ],
    },
    social: [
      { platform: "Facebook", href: "#" },
      { platform: "Twitter", href: "#" },
      { platform: "Instagram", href: "#" },
      { platform: "YouTube", href: "#" },
    ],
    copyright: "© 2024 Little Nezha Academy. All rights reserved.",
  },
}

export type LandingPageContent = typeof landingPageContent
